### ISSUE TITLE
Node1Config.ps1 run failed

### ISSUE THREAD

**Issue by john143143** [aws-quickstart/quickstart-microsoft-sql#95]
Node1Config.ps1 is failing with the below issue:

PowerShell DSC resource **MSFT_GroupResource**  failed to execute **Set-TargetResource** functionality with error message: 
Exception calling "Add" with "1" argument(s): "The network path was not found.
" 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

**- We are using custom domain managed through AWS EC2 instances
- Error from the EC2 log**

VERBOSE: [MSSQLN1]:                            [[xCluster]CreateCluster] Checking if the node MSSQLN1 is a member of the cluster MSSQLCluster1, and so that node status is 'Up'.
VERBOSE: [MSSQLN1]:                            [[xCluster]CreateCluster]    at MS.Internal.ServerClusters.NativeMethods.OpenCluster(String clusterName, ClusterAccessRights desiredAccess, ClusterAccessRights& grantedAccess)
   at MS.Internal.ServerClusters.Cluster.Open(String clusterName, ClusterAccessRights desiredAccess)
   at Microsoft.FailoverClusters.PowerShell.ClusterBridge.Open(String name, ClusterAccessRights desiredAccess)
   at Microsoft.FailoverClusters.PowerShell.ClusterPipeCmdlet.get_Clus()
   at Microsoft.FailoverClusters.PowerShell.GetNodeCommand.WrappedProcessRecord()
   at Microsoft.FailoverClusters.PowerShell.FCCmdlet.ProcessRecord()
Check the spelling of the cluster name. Otherwise, there might be a problem with your network. Make sure the cluster nodes are turned on and connected to the network or contact your network administrator.
    + CategoryInfo          : ConnectionError: (:) [], CimException
    + FullyQualifiedErrorId : ClusterRpcConnection,Microsoft.FailoverClusters.PowerShell.GetNodeCommand
    + PSComputerName        : localhost
 
VERBOSE: [MSSQLN1]:                            [[xCluster]CreateCluster] Cluster node MSSQLN1 is NOT a member of cluster MSSQLCluster1.
VERBOSE: [MSSQLN1]: LCM:  [ End    Test     ]  [[xCluster]CreateCluster]  in 4.7210 seconds.
The PowerShell DSC resource '[xCluster]CreateCluster' with SourceInfo 
'C:\ProgramData\Amazon\SSM\InstanceData\i-xxxxxxxxxx\document\orchestration\xxxxxxxx-37767cb5195b\downloads\Node1Config.ps1::129::9::xCluster' threw one or more non-terminating errors while running the 
Test-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
VERBOSE: [MSSQLN1]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 17.79 seconds

**Node1Config.ps1 -> line num 129**

        xCluster CreateCluster {
            Name                          =  $ClusterName
            StaticIPAddress               =  $WSFCNode1PrivateIP2
            DomainAdministratorCredential =  $Credentials
            DependsOn                     = '[Group]Administrators'
        }

Can someone help me in understanding the issue and the possible fix for the issue.

**Comment by AbdelrahmanElhais-rackspace** [comment]
any updates about this issue ?
